services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    stop_signal: SIGKILL
    environment:
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
      HIP_VISIBLE_DEVICES: "0"
    # devices:
    #   - "/dev/kfd"
    #   - "/dev/dri"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ipc: host
    group_add:
      - video
    volumes:
      - ./.docker/data_ollama:/root/.ollama
      - ./.docker/ollama.entrypoint.sh:/entrypoint.sh
    networks:
      - llm-network
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # command: serve
    # Auto-pull models on startup
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  download-sd1.5:
    build: ./.docker/sd1.5-download
    command: ["/entrypoint.sh", "download-sd1.5"]
    volumes:
      - ./.docker/data_stable-diffusion:/data
    networks:
      - llm-network

  # sd1.5
  sd-api:
    build: ./.docker/AUTOMATIC1111
    tty: true
    stop_signal: SIGKILL
    ports:
      - "7860:7860"
    volumes:
      - ./.docker/data_stable-diffusion:/data
    environment:
      - CLI_ARGS=--api --skip-install --medvram --xformers --allow-code
    networks:
      - llm-network
    # deploy:
    #   resources:
    #     # limits:
    #     #   cpus: '4'
    #     #   memory: 16G
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [compute, utility, gpu]
    depends_on:
      - download-sd1.5

  # sdxl
  # sd-api:
  #   image: saladtechnologies/sdnext-sdxl10:latest
  #   ports:
  #     - "7860:7860"
  #   environment:
  #     - PORT=7860
  #     - HOST=0.0.0.0
  #   volumes:
  #     - sdxl_data:/root/.cache/sdnext
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   networks:
  #     - llm-network

networks:
  llm-network:
    driver: bridge
